### ISSUE TITLE
Crash - unable to open music .ogg files

### ISSUE THREAD

**Issue by stoiandan** [pokemium/OpenPokemonRed#35]
I can build the project on Windows 10 via `make build-windows`, however, when I run the exe:

> 
> dan@dan-laptop MINGW64 ~/git/OpenPokemonRed (master)
> $ ./build/windows-amd64/pokered.exe 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal 0xc0000005 code=0x0 addr=0x18 pc=0x11150b7]
> 
> goroutine 1 [running, locked to thread]:
> pokered/pkg/audio.newMusic(0x0, 0x0, 0x11bf183, 0xf, 0x11bbfb0, 0x8, 0x0)
>         C:/Users/dan/git/OpenPokemonRed/pkg/audio/music.go:62 +0x57
> pokered/pkg/audio.newMusicMap(0xac44)
>         C:/Users/dan/git/OpenPokemonRed/pkg/audio/music.go:31 +0x7c
> pokered/pkg/audio.init()
>         C:/Users/dan/git/OpenPokemonRed/pkg/audio/music.go:24 +0x4b

I've looked into it and it looks like the `func newMusic` in  `music.go` is crashing, probably unable to find the file?
I'm not sure what the music paths represent (for example `/1-00 Intro.ogg`), where are this files supposed to be located?
I can't find any .ogg file in the project.

**Comment by Plloi** [comment]
This is is due to the removal of nintendo assets as noted in the readme:

12/27: This cannot be played now! Since this repo uses Nintendo assets, I have temporarily suspended the publish of encrypted asset file. Please wait until I come up with a good solution ...
